name: Build and Sign macOS App

on:
  push:
    tags:
    - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Import distribution certificate
      env:
        DEVELOPER_ID_CERT_BASE64: ${{ secrets.DEVELOPER_ID_CERT_BASE64 }}
        DEVELOPER_ID_CERT_PASSWORD: ${{ secrets.DEVELOPER_ID_CERT_PASSWORD }}
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      run: |
        echo "$DEVELOPER_ID_CERT_BASE64" | base64 --decode > certificate.p12
        security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
        security import certificate.p12 -k build.keychain -P "$DEVELOPER_ID_CERT_PASSWORD" -T /usr/bin/codesign
        security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" build.keychain

    - name: Update project version based on tag
      run: |
        TAG_VERSION=$(echo "${GITHUB_REF#refs/tags/v}")
        xcrun agvtool new-version -all "$TAG_VERSION"
        xcrun agvtool new-marketing-version "$TAG_VERSION"

    - name: Build app
      run: |
        xcodebuild -project NowPlayingMenuBar.xcodeproj -configuration Release

    - name: Sign app
      env:
        CODESIGN_IDENTITY: ${{ secrets.CODESIGN_IDENTITY }}
      run: |
        codesign -f -s "$CODESIGN_IDENTITY" build/Release/NowPlayingMenuBar.app --options runtime

    - name: Notarize app
      env:
        APP_DEVELOPER_ID: ${{ secrets.APP_DEVELOPER_ID }}
        APP_DEVELOPER_TEAM_ID: ${{ secrets.APP_DEVELOPER_TEAM_ID }}
        NOTARYTOOL_PASSWORD: ${{ secrets.NOTARYTOOL_PASSWORD }}
      run: |
        ditto -c -k --keepParent build/Release/NowPlayingMenuBar.app NowPlayingMenuBar-Unnotarized.zip
        xcrun notarytool submit NowPlayingMenuBar-Unnotarized.zip --apple-id "$APP_DEVELOPER_ID" --password "$NOTARYTOOL_PASSWORD" --team-id "$APP_DEVELOPER_TEAM_ID" --wait

    - name: Staple notarization ticket
      run: |
        xcrun stapler staple build/Release/NowPlayingMenuBar.app

    - name: Archive app
      run: |
        ditto -c -k --keepParent build/Release/NowPlayingMenuBar.app NowPlayingMenuBar.zip

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        files: |
          NowPlayingMenuBar.zip
