name: "tagged-release"

on:
  push:
    tags:
      - "v*"

permissions:
  id-token: "write"
  contents: "write"
  packages: "write"
  pull-requests: "read"

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Import Apple Distribution Certificate
      env:
        DIST_CERTIFICATE_BASE64: ${{ secrets.DIST_CERTIFICATE_BASE64 }}
        DIST_CERTIFICATE_PASSWORD: ${{ secrets.DIST_CERTIFICATE_PASSWORD }}
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      run: |
        echo $DIST_CERTIFICATE_BASE64 | base64 --decode > certificate.p12
        security create-keychain -p $KEYCHAIN_PASSWORD build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p $KEYCHAIN_PASSWORD build.keychain
        security import certificate.p12 -k build.keychain -P $DIST_CERTIFICATE_PASSWORD -T /usr/bin/codesign
        security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k $KEYCHAIN_PASSWORD build.keychain

    - name: Build App
      run: |
        xcodebuild -project NowPlayingMenuBar.xcodeproj -configuration Release

    - name: Sign App
      env:
        CODESIGN_IDENTITY: ${{ secrets.CODESIGN_IDENTITY }}
      run: |
        codesign -f -s "$CODESIGN_IDENTITY" build/Release/NowPlayingMenuBar.app

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: latest
        files: |
          build/Release/NowPlayingMenuBar.app
